apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: python_img
